language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t wad3inthewater/docker-learing -f Dockerfile.dev . #gets back an id each time docker build runs

script:
  - docker run -e CI=true wad3inthewater/docker-learing npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-app"
  env: "Dockerapp-env-2"
  bucket_name: "elasticbeanstalk-us-east-1-298327392140"
  bucket_path: "docker-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
# script:
#   - docker run USERNAME/docker-react npm run test -- --coverage
# access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY
